const tree = [
  {
    id: 1391,
    name: "英语语法",
    parentId: 0,
    sort: 1,
    grade: 1,
    isOpen: false,
    children: [
      {
        id: 1404,
        name: "（一）名词",
        parentId: 1391,
        sort: 1,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1405,
            name: "1.可数名词及其单复数",
            parentId: 1404,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1406,
            name: "2.不可数名词",
            parentId: 1404,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1407,
            name: "3.专有名词",
            parentId: 1404,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1408,
            name: "4.名词所有格",
            parentId: 1404,
            sort: 4,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1409,
        name: "（二）代词",
        parentId: 1391,
        sort: 2,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1410,
            name: "1.人称代词",
            parentId: 1409,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1411,
            name: "2.物主代词",
            parentId: 1409,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1412,
            name: "3.反身代词",
            parentId: 1409,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1413,
            name: "4.指示代词",
            parentId: 1409,
            sort: 4,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1414,
            name: "5.不定代词",
            parentId: 1409,
            sort: 5,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1415,
            name: "6.疑问代词",
            parentId: 1409,
            sort: 6,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1416,
        name: "（三）数词",
        parentId: 1391,
        sort: 3,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1417,
            name: "1.基数词",
            parentId: 1416,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1418,
            name: "2.序数词",
            parentId: 1416,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1419,
        name: "（四）介词和介词短语",
        parentId: 1391,
        sort: 4,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1420,
            name: "介词和介词短语",
            parentId: 1419,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1421,
        name: "（五）连词",
        parentId: 1391,
        sort: 5,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1422,
            name: "连词",
            parentId: 1421,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1423,
        name: "（六）形容词",
        parentId: 1391,
        sort: 6,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1424,
            name: "形容词（包括比较级和最高级）",
            parentId: 1423,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1425,
        name: "（七）副词",
        parentId: 1391,
        sort: 7,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1426,
            name: "副词（包括比较级和最高级）",
            parentId: 1425,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1427,
        name: "（八）冠词",
        parentId: 1391,
        sort: 8,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1428,
            name: "冠词",
            parentId: 1427,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1429,
        name: "（九）动词",
        parentId: 1391,
        sort: 9,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1430,
            name: "1.动词的基本形式",
            parentId: 1429,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1431,
            name: "2.系动词",
            parentId: 1429,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1432,
            name: "3.及物动词和不及物动词",
            parentId: 1429,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1433,
            name: "4.助动词",
            parentId: 1429,
            sort: 4,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1434,
            name: "5.情态动词",
            parentId: 1429,
            sort: 5,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1435,
            name: "6.时态",
            parentId: 1429,
            sort: 6,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1436,
            name: "7.被动语态",
            parentId: 1429,
            sort: 7,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1437,
            name: "8.非谓语动词",
            parentId: 1429,
            sort: 8,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1438,
            name: "9.动词短语",
            parentId: 1429,
            sort: 9,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1439,
        name: "（十）构词法",
        parentId: 1391,
        sort: 10,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1440,
            name: "1.前缀、后缀",
            parentId: 1439,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1441,
            name: "2.转化",
            parentId: 1439,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1442,
            name: "3.合成",
            parentId: 1439,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1443,
        name: "（十一）句子种类",
        parentId: 1391,
        sort: 11,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1444,
            name: "1.陈述句",
            parentId: 1443,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1445,
            name: "2.疑问句",
            parentId: 1443,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1446,
            name: "3.祈使句",
            parentId: 1443,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1447,
            name: "4.感叹句",
            parentId: 1443,
            sort: 4,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1448,
        name: "（十二）简单句的基本句型",
        parentId: 1391,
        sort: 12,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1449,
            name: "1.主语＋系动词和表语",
            parentId: 1448,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1450,
            name: "2.主语＋不及物动词",
            parentId: 1448,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1451,
            name: "3.主语＋及物动词＋宾语",
            parentId: 1448,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1452,
            name: "4.主语＋及物动词＋间接宾语＋直接宾语",
            parentId: 1448,
            sort: 4,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1453,
            name: "5.主语＋及物动词＋宾语＋宾语补足语",
            parentId: 1448,
            sort: 5,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1454,
            name: "6.there be句型",
            parentId: 1448,
            sort: 6,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1455,
        name: "（十三）并列复合句",
        parentId: 1391,
        sort: 13,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1456,
            name: "并列复合句",
            parentId: 1455,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1457,
        name: "（十四）主从复合句",
        parentId: 1391,
        sort: 14,
        grade: 3,
        isOpen: false,
        children: [
          {
            id: 1458,
            name: "1.宾语从句",
            parentId: 1457,
            sort: 1,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1459,
            name: "2.状语从句",
            parentId: 1457,
            sort: 2,
            grade: 4,
            isOpen: false,
            children: null,
          },
          {
            id: 1460,
            name: "3.定语从句",
            parentId: 1457,
            sort: 3,
            grade: 4,
            isOpen: false,
            children: null,
          },
        ],
      },
    ],
  },
  {
    id: 1484,
    name: "人教版（PEP）",
    parentId: 0,
    sort: 1,
    grade: 1,
    isOpen: false,
    children: [
      {
        id: 1488,
        name: "三年级上册",
        parentId: 1484,
        sort: 1,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1507,
            name: "U1-Hello!",
            parentId: 1488,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1508,
            name: "U2-Colous",
            parentId: 1488,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1509,
            name: "U3-Look at me!",
            parentId: 1488,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1510,
            name: "U4-We love animals",
            parentId: 1488,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1511,
            name: "U5-Let's eat！",
            parentId: 1488,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1512,
            name: "U6-Happy birthday！",
            parentId: 1488,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1487,
        name: "三年级下册",
        parentId: 1484,
        sort: 2,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1501,
            name: "U1-Welcome back to school",
            parentId: 1487,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1502,
            name: "U2-My family",
            parentId: 1487,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1503,
            name: "U3-At the zoo",
            parentId: 1487,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1504,
            name: "U4-Where is my car？",
            parentId: 1487,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1505,
            name: "U5-Do you like pears？",
            parentId: 1487,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1506,
            name: "U6-How many?",
            parentId: 1487,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1485,
        name: "四年级上册",
        parentId: 1484,
        sort: 3,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1489,
            name: "U1-My classroom",
            parentId: 1485,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1490,
            name: "U2-My-schoolbag",
            parentId: 1485,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1491,
            name: "U3-My friends",
            parentId: 1485,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1492,
            name: "U4-My home",
            parentId: 1485,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1493,
            name: "U5-Dinner's ready",
            parentId: 1485,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1494,
            name: "U6-Meet my family",
            parentId: 1485,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1486,
        name: "四年级下册",
        parentId: 1484,
        sort: 4,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1495,
            name: "U1-My school",
            parentId: 1486,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1496,
            name: "U2-What time is it",
            parentId: 1486,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1497,
            name: "U3-Weather",
            parentId: 1486,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1498,
            name: "U4-At the farm",
            parentId: 1486,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1499,
            name: "U5-My clothes",
            parentId: 1486,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1500,
            name: "U6-Shopping",
            parentId: 1486,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1387,
        name: "五年级上册",
        parentId: 1484,
        sort: 5,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1392,
            name: "U1-What's he like？",
            parentId: 1387,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1393,
                name: "性格和外貌",
                parentId: 1392,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1394,
            name: "U2-My week",
            parentId: 1387,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1399,
                name: "行程安排",
                parentId: 1394,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1395,
            name: "U3-What would you like?",
            parentId: 1387,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1400,
                name: "食物偏好",
                parentId: 1395,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1396,
            name: "U4-What can you do？",
            parentId: 1387,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1401,
                name: "能力和兴趣",
                parentId: 1396,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1397,
            name: "U5-There is a big bed",
            parentId: 1387,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1402,
                name: "生活环境",
                parentId: 1397,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1398,
            name: "U6-In a nature park",
            parentId: 1387,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1403,
                name: "人与自然",
                parentId: 1398,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
        ],
      },
      {
        id: 1388,
        name: "五年级下册",
        parentId: 1484,
        sort: 6,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1473,
            name: "U1-My day",
            parentId: 1388,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1479,
                name: "常规",
                parentId: 1473,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1474,
            name: "U2- My Favourite seasom",
            parentId: 1388,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1480,
                name: "四季、活动",
                parentId: 1474,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1475,
            name: "U3-My school calendar",
            parentId: 1388,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1481,
                name: "月份",
                parentId: 1475,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1476,
            name: "U4-When is the art show？",
            parentId: 1388,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1482,
                name: "日期",
                parentId: 1476,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1477,
            name: "U5-Whose dog is it？",
            parentId: 1388,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1478,
            name: "U6-Work quietly",
            parentId: 1388,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
      {
        id: 1389,
        name: "六年级上册",
        parentId: 1484,
        sort: 7,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1461,
            name: "U1-How can I get there？",
            parentId: 1389,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1462,
                name: "位置",
                parentId: 1461,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1463,
            name: "U2-Ways to go to school",
            parentId: 1389,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1464,
                name: "交通规则",
                parentId: 1463,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1465,
            name: "U3-My weekend plan",
            parentId: 1389,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1466,
                name: "计划",
                parentId: 1465,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1467,
            name: "U4-I have a pen pal",
            parentId: 1389,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1468,
                name: "朋友的爱好",
                parentId: 1467,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1469,
            name: "U5-What doer he do？",
            parentId: 1389,
            sort: 5,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1470,
                name: "职业",
                parentId: 1469,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
          {
            id: 1471,
            name: "U6-How do you feel",
            parentId: 1389,
            sort: 6,
            grade: 3,
            isOpen: false,
            children: [
              {
                id: 1472,
                name: "情感",
                parentId: 1471,
                sort: 1,
                grade: 4,
                isOpen: false,
                children: null,
              },
            ],
          },
        ],
      },
      {
        id: 1390,
        name: "六年级下册",
        parentId: 1484,
        sort: 8,
        grade: 2,
        isOpen: false,
        children: [
          {
            id: 1513,
            name: "U1-How tall are you?",
            parentId: 1390,
            sort: 1,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1514,
            name: "U2-Last weekend",
            parentId: 1390,
            sort: 2,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1515,
            name: "U3-Where did you go？",
            parentId: 1390,
            sort: 3,
            grade: 3,
            isOpen: false,
            children: null,
          },
          {
            id: 1516,
            name: "U4-Then and now",
            parentId: 1390,
            sort: 4,
            grade: 3,
            isOpen: false,
            children: null,
          },
        ],
      },
    ],
  },
];
const id = 1507;

const findParentNode = (data, id, ret) => {
  let arr = Array.from(ret);
  for (let index = 0; index < data.length; index++) {
    const element = data[index];
    arr.push(element.id);
    if (element.id === id) {
      return arr;
    }
    let children = element.children;
    if (children && children.length) {
      let result = findParentNode(children, id, arr);
      if (result) return result;
    }
    arr.pop();
  }
  return false;
};

console.log(findParentNode(tree, 1516, []));
